node('docker02.woodez.net') {
   def commit_id
   stage('Preperation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }

   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("kwood475/healthapi:latest", '.').push()
     }
   }

   stage('docker stop container') {
     sh 'docker container rm -f healthapi'
   }
   stage('docker run container') {
     def apiContainer = docker.image("kwood475/healthapi:latest").run("--name healthapi --publish 5000:5000")
   }


}